name: Build ESP32 Hello World
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
