name: Build ESP32 Hello World
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echeckout repository
      uses: actions/checkout@v2
        
    - name: Setup ESP-IDF
      uses: espressif/esp-idf@v5
      with:
        esp-idf-version: 'v5.1'
        
    - name: Configure Target
      run: |
        idf.py set-target esp32
        idf.py fullclean

    - name: Build project
      run: idf.py build

    - name: Flash and monitor
      run: idf.py -p /dev/ttyUSB0 flash monitor
